/**
 * Cult Clothing — Product catalog built from actual product folders
 * Real products come FIRST, AI-generated fillers come AFTER
 */

export const DUMMY_PRODUCTS = [
  // ═══════════════════════════════════════════════
  // REAL PRODUCTS — From d:\cult\products\ folders
  // ═══════════════════════════════════════════════

  // ─── FLORAL PRINT SHIRTS (8 images = multiple colors) ───
  {
    id: 'floral-shirt-001',
    name: 'Floral Print Shirt',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'shirts',
    price: 1499,
    originalPrice: 1999,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black Floral', 'White Floral', 'Navy Floral', 'Maroon Floral'],
    badge: 'BESTSELLER',
    fit: 'Regular Fit',
    stock: 40,
    collection: 'summer-shirts',
    description: 'Premium floral printed shirts with vibrant patterns. Perfect for casual outings and weekend vibes.',
    images: [
      '/catalog/floral-shirts/1.jpg',
      '/catalog/floral-shirts/2.jpg',
      '/catalog/floral-shirts/3.jpg',
      '/catalog/floral-shirts/4.jpg',
      '/catalog/floral-shirts/5.jpg',
      '/catalog/floral-shirts/6.jpg',
      '/catalog/floral-shirts/7.jpg',
      '/catalog/floral-shirts/8.jpg',
    ],
    colorImages: {
      'Black Floral': 0,
      'White Floral': 2,
      'Navy Floral': 4,
      'Maroon Floral': 6,
    },
  },

  // ─── CHECK SHIRTS (8 images = multiple colors) ───
  {
    id: 'check-shirt-001',
    name: 'Check Shirt',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'shirts',
    price: 1299,
    originalPrice: 1799,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue Check', 'Red Check', 'Green Check', 'Brown Check'],
    badge: 'NEW',
    fit: 'Regular Fit',
    stock: 50,
    collection: null,
    description: 'Classic check pattern shirts crafted from premium cotton. Timeless style for every occasion.',
    images: [
      '/catalog/check-shirts/1.jpg',
      '/catalog/check-shirts/2.jpg',
      '/catalog/check-shirts/3.jpg',
      '/catalog/check-shirts/4.jpg',
      '/catalog/check-shirts/5.jpg',
      '/catalog/check-shirts/6.jpg',
      '/catalog/check-shirts/7.jpg',
      '/catalog/check-shirts/8.jpg',
    ],
    colorImages: {
      'Blue Check': 0,
      'Red Check': 2,
      'Green Check': 4,
      'Brown Check': 6,
    },
  },

  // ─── LINEN SHIRTS (5 images = multiple colors) ───
  {
    id: 'linen-shirt-001',
    name: 'Linen Shirt',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'shirts',
    price: 1599,
    originalPrice: 2199,
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Beige', 'Sky Blue'],
    badge: 'TRENDING',
    fit: 'Relaxed Fit',
    stock: 30,
    collection: 'summer-shirts',
    description: 'Breathable linen shirts in soft pastel tones. Lightweight comfort perfect for Vizag summers.',
    images: [
      '/catalog/linen-shirts/1.jpg',
      '/catalog/linen-shirts/2.jpg',
      '/catalog/linen-shirts/3.jpg',
      '/catalog/linen-shirts/4.jpg',
      '/catalog/linen-shirts/5.jpg',
    ],
    colorImages: {
      'White': 0,
      'Beige': 2,
      'Sky Blue': 4,
    },
  },

  // ─── ZIPPER SHIRTS (5 images = multiple colors) ───
  {
    id: 'zipper-shirt-001',
    name: 'Zipper Shirt',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'shirts',
    price: 1699,
    originalPrice: 2299,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'White', 'Navy'],
    badge: 'EXCLUSIVE',
    fit: 'Slim Fit',
    stock: 25,
    collection: 'cult-classics',
    description: 'Trendy zipper detail shirts with a modern edge. Stand out from the crowd with this unique design.',
    images: [
      '/catalog/zipper-shirts/1.jpg',
      '/catalog/zipper-shirts/2.jpg',
      '/catalog/zipper-shirts/3.jpg',
      '/catalog/zipper-shirts/4.jpg',
      '/catalog/zipper-shirts/5.jpg',
    ],
    colorImages: {
      'Black': 0,
      'White': 2,
      'Navy': 4,
    },
  },

  // ─── T-SHIRTS (14 images = many colors) ───
  {
    id: 'tshirt-001',
    name: 'Printed T-Shirt Collection',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 't-shirts',
    price: 799,
    originalPrice: 1199,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Grey', 'Navy', 'Olive', 'Maroon', 'Red'],
    badge: 'BESTSELLER',
    fit: 'Oversized Fit',
    stock: 100,
    collection: 'cult-classics',
    description: 'Trendy printed t-shirts in multiple colors. Premium cotton with bold designs for everyday streetwear.',
    images: [
      '/catalog/tshirts/1.jpg',
      '/catalog/tshirts/3.jpg',
      '/catalog/tshirts/5.jpg',
      '/catalog/tshirts/6.jpg',
      '/catalog/tshirts/7.jpg',
      '/catalog/tshirts/8.jpg',
      '/catalog/tshirts/9.jpg',
      '/catalog/tshirts/10.jpg',
      '/catalog/tshirts/11.jpg',
      '/catalog/tshirts/12.jpg',
      '/catalog/tshirts/13.jpg',
      '/catalog/tshirts/14.jpg',
      '/catalog/tshirts/15.jpg',
      '/catalog/tshirts/16.jpg',
    ],
    colorImages: {
      'Black': 0,
      'White': 2,
      'Grey': 4,
      'Navy': 6,
      'Olive': 8,
      'Maroon': 10,
      'Red': 12,
    },
  },

  // ─── SWEATSHIRTS (3 images) ───
  {
    id: 'sweatshirt-001',
    name: 'Back Printed Sweatshirt',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 't-shirts',
    price: 1299,
    originalPrice: 1799,
    sizes: ['M', 'L', 'XL'],
    colors: ['Black', 'Grey'],
    badge: 'NEW',
    fit: 'Oversized Fit',
    stock: 35,
    collection: 'culture-code',
    description: 'Premium back printed sweatshirts with bold graphic designs. Heavy-weight fleece for cozy comfort.',
    images: [
      '/catalog/sweatshirts/1.jpg',
      '/catalog/sweatshirts/2.jpg',
      '/catalog/sweatshirts/3.jpg',
    ],
    colorImages: {
      'Black': 0,
      'Grey': 2,
    },
  },

  // ─── BARREL FIT BAGGYS (12 images = multiple colors) ───
  {
    id: 'barrel-baggy-001',
    name: 'Barrel Fit Baggys',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'pants',
    price: 1899,
    originalPrice: 2499,
    sizes: ['28', '30', '32', '34'],
    colors: ['Black', 'Charcoal', 'Khaki', 'Olive', 'Brown', 'Navy'],
    badge: 'TRENDING',
    fit: 'Barrel Fit',
    stock: 40,
    collection: 'korean-collection',
    description: 'Barrel fit baggy pants with a Korean-inspired silhouette. Premium fabric with relaxed comfortable fit.',
    images: [
      '/catalog/barrel-fit-baggys/1.jpg',
      '/catalog/barrel-fit-baggys/2.jpg',
      '/catalog/barrel-fit-baggys/3.jpg',
      '/catalog/barrel-fit-baggys/4.jpg',
      '/catalog/barrel-fit-baggys/5.jpg',
      '/catalog/barrel-fit-baggys/6.jpg',
      '/catalog/barrel-fit-baggys/7.jpg',
      '/catalog/barrel-fit-baggys/8.jpg',
      '/catalog/barrel-fit-baggys/9.jpg',
      '/catalog/barrel-fit-baggys/10.jpg',
      '/catalog/barrel-fit-baggys/11.jpg',
      '/catalog/barrel-fit-baggys/12.jpg',
    ],
    colorImages: {
      'Black': 0,
      'Charcoal': 2,
      'Khaki': 4,
      'Olive': 6,
      'Brown': 8,
      'Navy': 10,
    },
  },

  // ─── DENIM BAGGYS (7 images = multiple colors) ───
  {
    id: 'denim-baggy-001',
    name: 'Denim Baggys',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'jeans',
    price: 2199,
    originalPrice: 2799,
    sizes: ['28', '30', '32', '34'],
    colors: ['Light Blue', 'Dark Blue', 'Black Wash'],
    badge: 'NEW',
    fit: 'Baggy Fit',
    stock: 30,
    collection: 'korean-collection',
    description: 'Premium denim baggy jeans with relaxed fit. All India delivery available.',
    images: [
      '/catalog/denim-baggys/1.jpg',
      '/catalog/denim-baggys/2.jpg',
      '/catalog/denim-baggys/3.jpg',
      '/catalog/denim-baggys/4.jpg',
      '/catalog/denim-baggys/5.jpg',
      '/catalog/denim-baggys/6.jpg',
      '/catalog/denim-baggys/7.jpg',
    ],
    colorImages: {
      'Light Blue': 0,
      'Dark Blue': 2,
      'Black Wash': 4,
    },
  },

  // ═══════════════════════════════════════════════
  // AI-GENERATED FILLER PRODUCTS (shown after real)
  // ═══════════════════════════════════════════════

  {
    id: 'ai-tshirt-001',
    name: 'Textured T-Shirt: Verizon',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 't-shirts',
    price: 1299,
    originalPrice: 1599,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'Black'],
    badge: null,
    fit: 'Oversized Fit',
    stock: 50,
    collection: null,
    description: 'Premium textured oversized tee with a contemporary silhouette.',
    images: ['/images/products/oversized-tee-navy.png'],
    colorImages: {},
  },
  {
    id: 'ai-tshirt-002',
    name: 'Oversized T-Shirt: Rose Wine',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 't-shirts',
    price: 899,
    originalPrice: 1199,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Rose', 'Beige'],
    badge: null,
    fit: 'Oversized Fit',
    stock: 60,
    collection: null,
    description: 'Premium heavy gauge fabric oversized tee in stunning rose wine shade.',
    images: ['/images/products/oversized-tee-pink.png'],
    colorImages: {},
  },
  {
    id: 'ai-shirt-001',
    name: 'Satin Shirt: State Of Mind',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'shirts',
    price: 1699,
    originalPrice: 2199,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black'],
    badge: null,
    fit: 'Relaxed Fit',
    stock: 30,
    collection: 'old-money',
    description: 'Luxurious satin shirt with contrast piping details.',
    images: ['/images/products/satin-shirt-white.png'],
    colorImages: {},
  },
  {
    id: 'ai-polo-001',
    name: 'Piping Polo: Royal Blue',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'polos',
    price: 1599,
    originalPrice: 1999,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Royal Blue', 'Black'],
    badge: null,
    fit: 'Oversized Fit',
    stock: 40,
    collection: null,
    description: 'Oversized polo with signature piping details.',
    images: ['/images/products/polo-blue.png'],
    colorImages: {},
  },
  {
    id: 'ai-jogger-001',
    name: 'Korean Joggers: Black',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'joggers',
    price: 1599,
    originalPrice: 1999,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Grey'],
    badge: null,
    fit: 'Korean Fit',
    stock: 40,
    collection: 'korean-collection',
    description: 'Premium interlock fabric Korean fit joggers.',
    images: ['/images/products/korean-joggers-black.png'],
    colorImages: {},
  },
  {
    id: 'ai-pants-001',
    name: 'Easy Pants: Kohl Black',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'pants',
    price: 1899,
    originalPrice: 2399,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Black', 'Navy'],
    badge: null,
    fit: 'Classic Fit',
    stock: 35,
    collection: 'office-edit',
    description: 'Smart casual easy pants with elastic waistband.',
    images: ['/images/products/easy-pants-black.png'],
    colorImages: {},
  },
  {
    id: 'ai-pants-002',
    name: 'Gurkha Pants: Cedar',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'pants',
    price: 2499,
    originalPrice: 2999,
    sizes: ['28', '30', '32', '34'],
    colors: ['Cedar', 'Olive'],
    badge: null,
    fit: 'Tapered Fit',
    stock: 20,
    collection: 'old-money',
    description: 'Premium Gurkha pants with double-tab adjustable waist.',
    images: ['/images/products/gurkha-pants-cedar.png'],
    colorImages: {},
  },
  {
    id: 'ai-shirt-002',
    name: 'Hawaiian Resort Shirt',
    brand: 'Cult Clothing',
    category: 'clothing',
    subcategory: 'shirts',
    price: 1499,
    originalPrice: 1999,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Multi'],
    badge: null,
    fit: 'Relaxed Fit',
    stock: 45,
    collection: 'summer-shirts',
    description: 'Vibrant tropical print resort shirt for the summer season.',
    images: ['/images/products/hawaiian-shirt.png'],
    colorImages: {},
  },
];

// ═══ Query Helpers ═══

export function getAllDummyProducts() {
  return DUMMY_PRODUCTS;
}

export function getDummyProductById(id) {
  return DUMMY_PRODUCTS.find(p => p.id === id) || null;
}

export function getDummyProductsBySubcategory(subcategory) {
  return DUMMY_PRODUCTS.filter(p => p.subcategory === subcategory);
}

export function getDummyFeaturedProducts() {
  return DUMMY_PRODUCTS.filter(p => ['BESTSELLER', 'TRENDING'].includes(p.badge));
}

export function getDummyNewArrivals() {
  return DUMMY_PRODUCTS.filter(p => ['NEW', 'EXCLUSIVE'].includes(p.badge));
}

export function getDummyProductsByCollection(slug) {
  return DUMMY_PRODUCTS.filter(p => p.collection === slug);
}
